/-
Phase 9-7 e2e driver. Calls every `#[leo4::export]` from the
Rust mini-solver crate and prints the results. The Lean wrapper
module `Leo4ExampleMiniSolverRust.Rust` is generated by
`leo4-rust-emit --emit-lean` (see ../README.md step 2).

Run with the four-step workflow from `SPEC/reverse-direction.md`
§7 — the README expands each step in concrete terms for this
demo.
-/

-- The wrapper file gets dropped in by `leo4-rust-emit --emit-lean`
-- with the default `--lean-module Leo4ExampleMiniSolverRust.Rust`
-- naming. Importing it pulls in `leo4RustCallRaw`'s @[extern]
-- declaration.
import Leo4ExampleMiniSolverRust.Rust

open Leo4ExampleMiniSolverRust.Rust

def main : IO Unit := do
  IO.println s!"leo4 reverse-direction demo — schema_hash = {schemaHash}"
  IO.println ""

  -- Scalar in / scalar out (bool).
  IO.println "is_prime:"
  for n in [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 97, 100, 7919, 7920] do
    let p ← is_prime n.toUInt64
    IO.println s!"  is_prime({n}) = {p}"
  IO.println ""

  -- Walk forward through primes.
  IO.println "next_prime:"
  for n in [(1 : UInt64), 2, 10, 13, 100, 1000] do
    let q ← next_prime n
    IO.println s!"  next_prime({n}) = {q}"
  IO.println ""

  -- Long-running inner loop on the Rust side.
  IO.println "count_primes_below:"
  for n in [(10 : UInt64), 100, 1000] do
    let c ← count_primes_below n
    IO.println s!"  count_primes_below({n}) = {c}"
  IO.println ""

  -- Option<u64> return.
  IO.println "factor_smallest:"
  for n in [(0 : UInt64), 1, 2, 15, 49, 97, 999983] do
    let f ← factor_smallest n
    IO.println s!"  factor_smallest({n}) = {f}"
