//! leo4-oxilean-build — build-time transpiler from OxiLean
//! Lean source to a Rust crate, per
//! `SPEC/rust-native-lean.md` §9.
//!
//! ## What this is
//!
//! The **transpile path** to leo4-rust-native: instead of
//! dispatching Lean calls into a live OxiLean evaluator at
//! runtime (the `leo4-oxilean` adapter's role, currently
//! blocked on upstream Hooks 1 + 2 per §7.1), this crate
//! reads a Lean source tree, walks the `@[leo4_export]`
//! declarations, and emits a plain Rust crate via
//! `oxilean-codegen::rust_target_backend::RustTargetBackend`.
//! The generated crate is an ordinary Rust library —
//! callable in-process, no `lean.h` C ABI, no OxiLean
//! runtime dep at the consumer's build site.
//!
//! Key insight from `oxilean-codegen` v0.1.2 inspection:
//! `lcnf_to_rust_type` maps to **pure Rust types**:
//! `Nat → U64`, `LcnfString → RustString`, `Object → Box<dyn
//! Any>`. No `lean_box` / `lean_object*` in the output. The
//! resulting Rust crate is structurally indistinguishable
//! from one a human would write.
//!
//! ## Status (2026-05-21)
//!
//! **SCAFFOLD**. Cargo deps wired (`oxilean-parse`,
//! `oxilean-elab`, `oxilean-codegen`, `oxilean-kernel`); the
//! type surface for the transpiler driver compiles; **but
//! no end-to-end transpile is wired yet**. The blocking
//! items are upstream API questions answered case-by-case
//! during real-fixture testing — they're not architectural
//! blockers (unlike Hooks 1 + 2 for the runtime-dispatch
//! sibling crate):
//!
//! 1. `oxilean-parse`'s public entry for parsing a Lean
//!    source file or string. The crate's public API surface
//!    needs surveying as the wiring proceeds.
//! 2. `oxilean-elab`'s public entry for elaborating parsed
//!    AST to LCNF. Hook 3 (attribute / deriving handler
//!    registration) ties in here.
//! 3. Driving the `LcnfModule` → `RustTargetBackend::
//!    emit_module` → `RustModule::emit() -> String` chain
//!    is documented in §9.1 / §9.3 of the SPEC; what's
//!    missing is the wrapper that walks a user package's
//!    Lean sources, registers the `@[leo4_export]` attribute
//!    handler, and writes the result to a destination Cargo
//!    crate dir.
//!
//! ## What works today
//!
//! - Cargo deps resolve + compile (5 OxiLean crates
//!   reachable).
//! - `transpile_decls(decls: &[LcnfFunDecl]) -> String`
//!   helper that uses `RustTargetBackend` against an
//!   already-lowered LCNF (skipping the parse + elab steps
//!   so it's testable without a Lean source corpus).
//! - Type-system check: every `lcnf_to_rust_type` mapping
//!   produces a Rust type that *names a real Rust standard
//!   type* (`u64`, `String`, `()`, `Box<dyn Any>`, `fn(…) ->
//!   …`) — verified via the `transpile_emits_no_lean_h`
//!   test.
//!
//! ## Activation plan (next commits)
//!
//! Once a real OxiLean source fixture exists in
//! `tests/fixtures/`:
//!
//! 1. Wire `oxilean-parse` to read the fixture.
//! 2. Wire `oxilean-elab` to elaborate it (registering a
//!    custom `@[leo4_export]` attribute handler).
//! 3. Walk the elaborated env, find every `@[leo4_export]`
//!    tag, hand its LCNF decls to `emit_module`.
//! 4. Wrap each emitted Rust fn with leo4-abi's
//!    canonical-ABI encode/decode glue so the result
//!    matches what a hand-written `#[leo4::export]` crate
//!    would produce.
//! 5. Write a `Cargo.toml` + lib.rs to a target directory.

#![allow(clippy::missing_errors_doc)]

use leo4_abi::LeanError;
use oxilean_codegen::lcnf::LcnfFunDecl;
use oxilean_codegen::rust_target_backend::{RustItem, RustTargetBackend};

/// Transpile a slice of LCNF function declarations to a
/// single Rust source string. Wraps
/// `RustTargetBackend::emit_module` + the `RustModule`'s
/// per-item `RustFn::emit()` serialisation.
///
/// `module_name` is used as the OxiLean-side module label;
/// it doesn't affect the emitted Rust source structure.
///
/// # Errors
/// `LeanError` if every decl in `decls` fails to compile
/// (the backend silently drops individually-failing decls,
/// so a totally-empty result is a sign of upstream
/// breakage).
pub fn transpile_decls(
    module_name: &str,
    decls: &[LcnfFunDecl],
) -> Result<String, LeanError> {
    let mut backend = RustTargetBackend::new();
    let module = backend.emit_module(module_name, decls);
    if module.items.is_empty() && !decls.is_empty() {
        return Err(LeanError::new(
            leo4_abi::error::error_codes::ENCODE_ERROR,
            format!(
                "leo4-oxilean-build: RustTargetBackend dropped every \
                 LCNF decl in `{module_name}` — none compiled to Rust"
            ),
        ));
    }
    let mut out = String::new();
    out.push_str("//! Auto-generated by leo4-oxilean-build from OxiLean source.\n");
    out.push_str("//! DO NOT EDIT — re-run the build step instead.\n\n");
    for item in &module.items {
        match item {
            RustItem::Fn(f) => {
                out.push_str(&f.emit());
                out.push_str("\n\n");
            }
            // Other RustItem variants (structs, enums, impls)
            // would be emitted via their own `emit()` methods
            // once the backend produces them. For the v0
            // surface — leo4 exports are top-level fns — only
            // RustItem::Fn appears.
            _ => {}
        }
    }
    Ok(out)
}

/// Sanity probe: does the backend's type mapper actually
/// produce Rust type names that don't reference `lean_*`
/// symbols? Used as a build-time invariant — if a future
/// OxiLean release flips `lcnf_to_rust_type(Nat)` to e.g.
/// `RustType::Custom("lean_box_uint64")`, this fn returns
/// `false` and the corresponding test catches the
/// regression.
#[must_use]
pub fn type_mapper_is_lean_h_free() -> bool {
    use oxilean_codegen::lcnf::LcnfType;

    let probes: &[LcnfType] = &[
        LcnfType::Nat,
        LcnfType::LcnfString,
        LcnfType::Unit,
        LcnfType::Erased,
    ];
    for probe in probes {
        let ty = RustTargetBackend::lcnf_to_rust_type(probe);
        let rendered = format!("{ty}");
        if rendered.contains("lean_")
            || rendered.contains("Lean_")
            || rendered.contains("lean.h")
        {
            return false;
        }
    }
    true
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn type_mapper_emits_pure_rust() {
        assert!(
            type_mapper_is_lean_h_free(),
            "RustTargetBackend's lcnf_to_rust_type must NOT emit lean_* symbols"
        );
    }

    #[test]
    fn nat_maps_to_u64() {
        use oxilean_codegen::lcnf::LcnfType;
        use oxilean_codegen::rust_target_backend::RustType;
        let ty = RustTargetBackend::lcnf_to_rust_type(&LcnfType::Nat);
        assert_eq!(ty, RustType::U64);
    }

    #[test]
    fn string_maps_to_rust_string() {
        use oxilean_codegen::lcnf::LcnfType;
        use oxilean_codegen::rust_target_backend::RustType;
        let ty = RustTargetBackend::lcnf_to_rust_type(&LcnfType::LcnfString);
        assert_eq!(ty, RustType::RustString);
    }

    #[test]
    fn transpile_empty_decls_returns_header_only() {
        let out = transpile_decls("empty", &[]).expect("empty must succeed");
        assert!(out.contains("Auto-generated"));
        assert!(out.contains("DO NOT EDIT"));
        // No fn definitions for an empty decl set.
        assert!(!out.contains("fn "));
    }
}
