//! OX8.2 — reverse direction wrapper emit.
//!
//! Drives the rust-transpile path's reverse direction:
//! a Rust cdylib that re-exports `#[leo4::export]` functions
//! via `EXPORTS` (declared in `crates/leo4-abi/src/rust_exports.rs`)
//! becomes a `lean/<Iface>/Rust.lean` file full of
//! `@[extern "<mangled>"]` decls, callable from a Lean
//! source running under `sibling/leo4-oxilean`'s OxiLean
//! evaluator.
//!
//! ## Why a different wrapper shape than mslean4 reverse?
//!
//! `crates/leo4-rust-emit/src/main.rs::render_lean_wrapper`
//! emits *dispatcher-based* wrappers: every Lean call goes
//! through a single `leo4_rust_call_lean` extern that
//! multiplexes mangled-name + canonical-ABI byte buffer.
//! That works because mslean4 has a Rust dispatcher binary
//! (`leo4-rust-worker`) eager-loaded behind the scenes.
//!
//! The rust-transpile path doesn't ship that worker — its
//! design goal is "no lake, no daemon, no separate
//! dispatcher process". So OX8 takes the simpler model:
//! each export gets its *own* `@[extern "<mangled>"]` decl
//! that resolves directly to the cdylib's C-linkage symbol.
//! The OxiLean evaluator (OX8.3, upstream-blocked) handles
//! the actual `libloading` dispatch.
//!
//! ## Status
//!
//! OX8.2a (this commit): lib-level renderer +
//! `ExportEntryView` decoupled from the live cdylib. CLI
//! plumbing — `--mode reverse` flag, cdylib loading via
//! `leo4_rust_describe_exports` — lands in OX8.2b.

/// Mirror of `leo4_abi::ExportEntry` (`crates/leo4-abi/src/
/// rust_exports.rs`) with `String` instead of `&'static
/// str`, so callers can decouple this module's tests from
/// a live cdylib load.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ExportEntryView {
    /// User-visible name. Matches Rust `fn` ident.
    pub logical_name: String,
    /// C-linkage symbol the OxiLean evaluator resolves via
    /// `dlsym`. Format:
    /// `leo4_rust__<fname>__<param_mangles>`.
    pub mangled: String,
    /// Parameter type mangles in declaration order.
    pub param_types: Vec<String>,
    /// Return type mangle. Empty string = unit.
    pub ret_type: String,
    /// `#[leo4::export(isolated)]` — informational only;
    /// reverse-emit doesn't change shape based on it (the
    /// rust-transpile reverse runner picks dispatch
    /// behaviour at runtime).
    pub isolated: bool,
    /// ABI version this entry was emitted against.
    /// Currently always `1`.
    pub abi_version: u32,
}

/// Render the full `lean/<Iface>/Rust.lean` wrapper from
/// a list of cdylib exports.
///
/// Each `@[extern "<mangled>"] opaque <name> (...) : ...`
/// is a typed binding to one Rust `#[leo4::export]`
/// function. The OxiLean evaluator at call time looks up
/// the mangled symbol in the configured cdylib via
/// `libloading` (OX8.3) and dispatches with the
/// canonical-ABI byte buffer.
///
/// `module` is the Lean namespace (typically
/// `<Iface>.Rust`).
///
/// Returns `Err` if any export has a parameter or return
/// mangle the type mapper doesn't recognise — caller can
/// then choose to skip the offending entries or fail the
/// build.
///
/// # Errors
/// Currently unused; reserved for future "strict mode"
/// where unmapped mangles abort. The current
/// implementation passes through unmapped mangles as
/// commented-out `String` placeholders (matching
/// `leo4-rust-emit`'s behaviour).
pub fn render_reverse_wrapper(
    module: &str,
    entries: &[ExportEntryView],
) -> Result<String, String> {
    let mut s = String::new();
    s.push_str("-- Auto-generated by `leo4-oxilean-build --mode reverse`. Do not edit.\n");
    s.push_str("-- See SPEC/ox8-rust-transpile-reverse.md.\n");
    s.push_str("--\n");
    s.push_str("-- Each `#[leo4::export]` Rust function in the source\n");
    s.push_str("-- cdylib surfaces here as one `@[extern]` opaque. The\n");
    s.push_str("-- OxiLean evaluator (`sibling/leo4-oxilean`) resolves\n");
    s.push_str("-- the mangled symbol at call time via `libloading`.\n\n");
    s.push_str(&format!("namespace {module}\n\n"));

    let mut sorted: Vec<&ExportEntryView> = entries.iter().collect();
    sorted.sort_by(|a, b| a.logical_name.cmp(&b.logical_name));
    for e in sorted {
        s.push_str(&render_one_extern(e));
        s.push('\n');
    }

    s.push_str(&format!("end {module}\n"));
    Ok(s)
}

/// Render one `@[extern] opaque` per export. The signature
/// is reconstructed from the entry's `param_types` /
/// `ret_type` mangles via `lean_type_of_mangle`.
fn render_one_extern(e: &ExportEntryView) -> String {
    let mut s = String::new();
    s.push_str(&format!(
        "/-- `{}` (mangled: `{}`). -/\n",
        e.logical_name, e.mangled,
    ));
    s.push_str(&format!("@[extern \"{}\"]\n", e.mangled));

    let fname = lean_safe_ident(&e.logical_name);
    s.push_str(&format!("opaque {fname}"));
    for (i, m) in e.param_types.iter().enumerate() {
        let lean_ty = lean_type_of_mangle(m)
            .unwrap_or_else(|| format!("/- unmapped: {m} -/ String"));
        s.push_str(&format!(" (a{i} : {lean_ty})"));
    }
    let ret_ty = if e.ret_type.is_empty() {
        "Unit".to_string()
    } else {
        lean_type_of_mangle(&e.ret_type)
            .unwrap_or_else(|| format!("/- unmapped: {} -/ Unit", e.ret_type))
    };
    s.push_str(&format!(" : {ret_ty}\n"));
    s
}

/// Mirror of `leo4-rust-emit`'s mangle → Lean type map.
/// Duplicated here rather than depending on `leo4-rust-emit`
/// because `leo4-oxilean-build` is a standalone sibling
/// crate (not a workspace member) and pulling in the
/// `leo4-rust-emit` crate would drag the full main-workspace
/// dep graph in.
///
/// Recognises sized integer / float / bool / char / string
/// / Int / Nat / List<u8> as ByteArray / List<T> as Array T
/// / Option<T> mangles. Returns `None` for anything
/// unrecognised; the renderer surfaces unmapped mangles as
/// `/- unmapped: <mangle> -/ String` placeholders.
pub fn lean_type_of_mangle(mangle: &str) -> Option<String> {
    Some(match mangle {
        "u8" => "UInt8".into(),
        "u16" => "UInt16".into(),
        "u32" => "UInt32".into(),
        "u64" => "UInt64".into(),
        "i8" => "Int8".into(),
        "i16" => "Int16".into(),
        "i32" => "Int32".into(),
        "i64" => "Int64".into(),
        "f32" => "Float32".into(),
        "f64" => "Float".into(),
        "b" => "Bool".into(),
        "c" => "Char".into(),
        "str" => "String".into(),
        "bI" => "Int".into(),
        "bN" => "Nat".into(),
        other => {
            // List<u8> → ByteArray; List<T> → Array T (best effort).
            if let Some(rest) =
                other.strip_prefix("L_").and_then(|r| r.strip_suffix("_l"))
            {
                if rest == "u8" {
                    return Some("ByteArray".into());
                }
                let inner = lean_type_of_mangle(rest)?;
                return Some(format!("Array {inner}"));
            }
            if let Some(rest) =
                other.strip_prefix("O_").and_then(|r| r.strip_suffix("_o"))
            {
                let inner = lean_type_of_mangle(rest)?;
                return Some(format!("Option {inner}"));
            }
            return None;
        }
    })
}

/// Avoid the literal Lean keyword collisions. Anything not
/// in the list passes through unchanged — Lean identifiers
/// otherwise overlap Rust's lexical set.
fn lean_safe_ident(s: &str) -> String {
    if matches!(
        s,
        "def" | "let" | "fun" | "match" | "if" | "then" | "else" |
        "do" | "open" | "namespace" | "section" | "end" | "import" |
        "where" | "with" | "by" | "instance" | "structure" | "inductive"
    ) {
        format!("`{s}`")
    } else {
        s.to_string()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn mk_entry(name: &str, mangled: &str, params: &[&str], ret: &str) -> ExportEntryView {
        ExportEntryView {
            logical_name: name.to_string(),
            mangled: mangled.to_string(),
            param_types: params.iter().map(|s| s.to_string()).collect(),
            ret_type: ret.to_string(),
            isolated: false,
            abi_version: 1,
        }
    }

    #[test]
    fn render_two_arith_exports_emits_namespace_and_decls() {
        let entries = vec![
            mk_entry("add", "leo4_rust__add__u64_u64", &["u64", "u64"], "u64"),
            mk_entry("dbl", "leo4_rust__dbl__u64", &["u64"], "u64"),
        ];
        let out = render_reverse_wrapper("Sample.Rust", &entries).unwrap();
        assert!(out.contains("namespace Sample.Rust\n"));
        assert!(out.contains("end Sample.Rust\n"));
        // Each export becomes one `@[extern "<mangled>"]
        // opaque <name>` line.
        assert!(out.contains("@[extern \"leo4_rust__add__u64_u64\"]"));
        assert!(out.contains("opaque add (a0 : UInt64) (a1 : UInt64) : UInt64"));
        assert!(out.contains("@[extern \"leo4_rust__dbl__u64\"]"));
        assert!(out.contains("opaque dbl (a0 : UInt64) : UInt64"));
        // Sorted by logical_name — `add` before `dbl`.
        let pos_add = out.find("opaque add").unwrap();
        let pos_dbl = out.find("opaque dbl").unwrap();
        assert!(pos_add < pos_dbl, "exports must sort by logical_name");
    }

    #[test]
    fn render_handles_unit_return_and_bool_param() {
        let entries = vec![mk_entry("check", "leo4_rust__check__b", &["b"], "")];
        let out = render_reverse_wrapper("X", &entries).unwrap();
        assert!(out.contains("opaque check (a0 : Bool) : Unit"));
    }

    #[test]
    fn render_handles_bytearray_via_list_u8() {
        let entries = vec![mk_entry(
            "hash",
            "leo4_rust__hash__L_u8_l",
            &["L_u8_l"],
            "L_u8_l",
        )];
        let out = render_reverse_wrapper("X", &entries).unwrap();
        assert!(out.contains("opaque hash (a0 : ByteArray) : ByteArray"));
    }

    #[test]
    fn render_handles_option_wrapper() {
        let entries = vec![mk_entry(
            "find",
            "leo4_rust__find__str",
            &["str"],
            "O_u64_o",
        )];
        let out = render_reverse_wrapper("X", &entries).unwrap();
        assert!(
            out.contains("opaque find (a0 : String) : Option UInt64"),
            "got:\n{out}"
        );
    }

    #[test]
    fn render_keyword_name_gets_raw_escape() {
        let entries = vec![mk_entry("end", "leo4_rust__end__", &[], "")];
        let out = render_reverse_wrapper("X", &entries).unwrap();
        assert!(out.contains("opaque `end` : Unit"), "got:\n{out}");
    }

    #[test]
    fn render_unmapped_mangle_surfaces_as_placeholder() {
        let entries = vec![mk_entry(
            "exotic",
            "leo4_rust__exotic__XYZ",
            &["XYZ"],
            "XYZ",
        )];
        let out = render_reverse_wrapper("X", &entries).unwrap();
        // Both param and return get the `/- unmapped: -/`
        // marker so the generated source stays buildable
        // (Lean parses comments cleanly) while flagging
        // the gap.
        assert!(out.contains("/- unmapped: XYZ -/"));
    }

    #[test]
    fn empty_exports_emits_namespace_skeleton() {
        let out = render_reverse_wrapper("Nothing", &[]).unwrap();
        assert!(out.contains("namespace Nothing"));
        assert!(out.contains("end Nothing"));
    }
}
