//! `wasmtime`-backed `WasmRuntime` impl. Gated on the
//! `backend-wasmtime` feature (default).
//!
//! Phase 10-C4.x scaffolding (2026-05-21): the trait impls return
//! `LEO4_ERR_RUST_DLSYM_FAILED` with a clear "not yet implemented"
//! message. The real impl lands in C4.x.x once
//! `SPEC/wit/leo4-host.wit` is pinned — at that point this module
//! pulls in the `wasmtime` crate (with `component-model` feature)
//! and wires `wasmtime::component::{Component, Engine, Linker,
//! Store}` behind the local trait.

use crate::runtime::{WasmComponent, WasmInstance, WasmRuntime};
use crate::LeanError;

/// Wasmtime-backed runtime. Zero-sized today; C4.x.x will hold
/// a `wasmtime::Engine` (which itself is cheap-to-clone, single
/// per process is conventional).
#[derive(Debug, Default, Clone, Copy)]
pub struct WasmtimeRuntime;

impl WasmtimeRuntime {
    /// Construct a runtime with wasmtime's default `Config`
    /// (Component Model + WASIp2 enabled when wired in C4.x.x).
    #[must_use]
    pub fn new() -> Self {
        Self
    }
}

impl WasmRuntime for WasmtimeRuntime {
    fn open_component(
        &self,
        _bytes: &[u8],
    ) -> Result<Box<dyn WasmComponent>, LeanError> {
        Err(LeanError::new(
            0x0002_0005,
            "leo4-wasm wasmtime backend: open_component not yet implemented \
             (Phase 10-C4.x.x pending SPEC/wit/leo4-host.wit design + \
             wit-bindgen-generated typed bindings).",
        ))
    }
}

/// Stub component handle. Real C4.x.x impl wraps
/// `wasmtime::component::Component`.
#[derive(Debug)]
pub struct WasmtimeComponent {
    _private: (),
}

impl WasmComponent for WasmtimeComponent {
    fn instantiate(&self) -> Result<Box<dyn WasmInstance>, LeanError> {
        Err(LeanError::new(
            0x0002_0005,
            "leo4-wasm wasmtime backend: instantiate not yet implemented (C4.x.x).",
        ))
    }
}

/// Stub instance handle. Real C4.x.x impl wraps a
/// `(wasmtime::Store, wasmtime::component::Instance)` pair plus
/// the typed bindings struct generated by `wit-bindgen`.
#[derive(Debug)]
pub struct WasmtimeInstance {
    _private: (),
}

impl WasmInstance for WasmtimeInstance {
    fn call(
        &mut self,
        mangled: &str,
        _args: &[u8],
    ) -> Result<Vec<u8>, LeanError> {
        Err(LeanError::new(
            0x0002_0005,
            format!(
                "leo4-wasm wasmtime backend: call({mangled}) not yet implemented (C4.x.x)."
            ),
        ))
    }
}
